# Generated by Django 4.1.1 on 2022-09-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_answer_type_task_reference_short_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='answer_type',
        ),
        migrations.AddField(
            model_name='task',
            name='detail_answer',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
