# Generated by Django 4.1.1 on 2022-09-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_answer_type_task_detail_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
