# Generated by Django 4.1.1 on 2022-09-18 22:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_rename_task_taskmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailedAnswer',
            new_name='Answer',
        ),
    ]
