# Generated by Django 4.1.1 on 2022-09-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_detailedanswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
