# Generated by Django 4.1.1 on 2022-09-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
