# Generated by Django 4.1.1 on 2022-09-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_taskmodel_status_answer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='make_public_responding_user',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='make_public_task_admin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
